### ISSUE TITLE
Google redirect obscures some searches

### ISSUE THREAD

**Issue by Urumasi** [Project-Path-of-Exile-Wiki/poe-wiki-search#9] opened 2021-09-15 18:15 UTC
Some searches, that would lead you to the original wiki's page instantly now show a bunch of unrelated poewiki pages

It would be nice if this was a toggle-able feature in the plugin's pop-out window
### Examples:
<details>
  <summary>Atziri's Mirror</summary>

![image](https://user-images.githubusercontent.com/8294011/133486567-bf3ced7f-b7ea-4fac-8d98-429ad38e443d.png)
</details>
<details>
  <summary>Armor</summary>

![image](https://user-images.githubusercontent.com/8294011/133486605-ae3e7491-29c1-415d-89da-e89bffebf73c.png)
</details>
<details>
  <summary>Mind over Matter</summary>

![image](https://user-images.githubusercontent.com/8294011/133486972-7c7dc007-cb0c-49ec-830c-552df0bd4b56.png)
</details>

**Comment by santos57** [comment] 2021-09-15 20:16
Seconding this for the additional reason that not all poe-related searches should target the wiki at all.

For example, searching "poe twitch" _should_ lead you to the path of exile directory and/or the path of exile twitch channel.
The google redirect instead tries to find twitch on the wiki, which obviously fails.

Searching "poe coc build" _should_ lead you to either the build forums or a youtube guide, but the google redirect instead shows the community shorthand wiki page.

You'll have similar problems trying to find poe related online tools online like poe profit and poe racing.

In general, I would say probably a bad idea to have this feature on by default if there at all since it poses a number of problems. Having it be togglable in the popout window as Urumasi suggests would be great, but in general it needs work to better target the proper search query.

I might also suggest triggering the redirect on google searches only if both terms ("poe" and "wiki") are present to avoid the issue of redirecting non-wiki related searches toward the wiki, though this is less necessary if the entire thing is on a toggle anyway since you'd just turn it on in the tray while doing wiki-related searches then off again later.

**Comment by pm5k** [comment] 2021-09-15 22:19
@Urumasi @santos57 
Thanks for getting in touch, we have identified a bug which has caused unrelated searches that include the “poe” keyword be incorrectly directed via the specificity site prefix; this was fixed and a 1.0.5 version has been submitted to both the Google and Moz web stores. All I can say is we apologise for the oversight and hope that once these are approved - users will seamlessly get the right behaviour back. We tested this internally between ourselves using FF, Chrome and Opera and confirmed it working as intended where writing “poe raizqt” for instance will bring up Raiz’s profile page on the main site instead of doing anything wiki related, but if you write “poewiki something” or “poe wiki something “ this will ensure the query gets the “site” prefix. 

We also want to introduce more than one toggle for an upcoming 1.0.6 version where users will selectively be able to decide whether they want to disable the site prefixer for searches, the global redirect for any anchors leading to fandom or both. This will be localStorage based and will probably increase the release time since both storefronts will have to review the extra permission request - but it should allow you to set these at any time and toggle as you please. 

Hth

**Comment by pm5k** [comment] 2021-09-15 22:25
@Urumasi an additional comment regarding the results: the wiki is still being indexed by Google crawlers, this is a slow process considering it’s size. As a result some of the searches are basically the best Google can do with what it has already indexed. As time goes by and more pages are pulled in and the SEO does it’s magic, we hope the accuracy will fall in line with what is expected. 

Hoping that this and the upcoming toggles will allow for a better experience.

**Comment by pm5k** [comment] 2021-09-16 21:43
Closing this as 1.0.6 is already out and fixes these issues, while the toggle is now covered by #8.

**Closed by pm5k** 2021-09-16 21:43 UTC
Labels: bug, fixed, fixversion:1.0.6
